import "./globals.css";

import HtmlContainer from "@/components/HtmlContainer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-Hant-TW">
      <HtmlContainer>{children}</HtmlContainer>
    </html>
  );
}
